server:
  port: 8080
   
   
spring:
  profiles:    
    active: 
    - ${SPRING_PROFILE:dev} 
# the dashes effectivley turns this single file into two files
---
  
spring:
  profiles: dev
  
  application:    
    name: FlashSale
  
  datasource:    
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:      
      ddl-auto: update
    properties:      
      hibernate:
        default_schema: ${DB_SCHEMA}
    show-sql: true
        

---

spring:
  profiles: prod
  
  application:
    name: DMPaperCompany
  
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
    show-sql: false